// template = - [header :your header as HTML] [description": "description goes here as HTML] ,... //multiple
const whats_new_log = `
- [Plugin] New Version History plugin: view the version history of an iFlow and revert to an earlier version directly in the editor. Special thanks to Gregor Schütz.
- [Plugin] New MPL Table Sorter plugin: sort the Monitor Message Processing table by one or more columns. Special thanks to Prem Sai Daggolu.
- [Plugin] New Create named Groovy script plugin: create a Groovy resource with a name of your choice in the current iFlow. Special thanks to Björn Konzmann.
- [Feature] New floating toolbar instead of the buttons in the page header: Trace, Messages, Info, Logs and Runtime in a toolbar you can drag anywhere. Wide with labels or compact with icons only, it remembers position and variant. In the compact variant hovering shows the name and the keyboard shortcut.
- [Feature] Everyone updating from version 3 gets a short welcome and a tour of the new toolbar, once. It can be replayed from What changed.
- [Feature] Plugins have their own section in the toolbar. Plugins with a single action run it directly, plugins with more content open it in a panel next to the toolbar. The plugin settings are under Manage plugins.
- [Feature] Message popup in the style of the new toolbar, slightly translucent. The header keeps the tenant color.
- [Feature] CPI Helper toolbar on the new API and MCP Server pages. They use the integration cell runtime by default.
- [Feature] Rewritten browser action popup: faster, without jQuery and Semantic UI, and it can open the plugin settings of the current tab. Artifact names in the popup are now escaped. Special thanks to Alexander Aigner.
- [Feature] The browser tab title shows a readable name of the current app. Thanks to Alexander Aigner.
- [Feature] For plugin developers: toolbarButton for direct toolbar actions, an optional icon for toolbar entries and a select dropdown for plugin settings. Thanks to Alexander Aigner.
- [Feature] New payload viewer for trace bodies, headers and attachments: pretty print that keeps CDATA, comments and big JSON numbers, search, fold, font size, wrap, fullscreen and a resizable editor that remembers its height.
- [Feature] Inline trace (experimental): new Changes tab shows side by side what a step did to body, headers and properties.
- [Feature] Inline trace: all steps of a message load, the first ones right away and the rest in the background (up to 5,000 instead of a fixed limit of 300). Steps with many runs, e.g. after a splitter, load a run only when it is opened.
- [Feature] Snippets (extremely experimental, danger zone): save steps you copied in the iFlow editor under a name, rename, edit, duplicate and share them as text, and put them back into the CPI clipboard to paste them into an Integration Process or Local Integration Process of any iFlow on the tenant. Uses internals of the SAP editor, a lot will not work; snippets with start elements (Timer, Start Message) only go into an Integration Process. You alone are responsible for what you do and what you break. Off by default, switched on in the danger zone of the settings.
- [Feature] Copy buttons on hover for names and values in trace, log and info tables.
- [Improvement] The setting "Plugin page as separate sidebar" is gone, plugins live in the toolbar now.
- [Improvement] Updated plugin metadata for Timeline, Unlock and Credential Helper. Thanks to Gregor Schütz.
- [Improvement] Version History highlights only the current version, Unlock refreshes the page after unlocking. Thanks to Gregor Schütz.
- [Improvement] jQuery and Fomantic UI are gone, about 3 MB less loaded into every CPI page. Dialogs and toasts take the look of the new toolbar and follow the light and dark CPI theme.
- [Improvement] More robust plugins: one failing plugin no longer affects the others.
- [Improvement] New trace icon in the toolbar. With more than one runtime the runtime button shows how many there are to switch to.
- [Improvement] Cleaner log viewer: filters with labels, a Refresh button and a flat message list grouped by day.
- [Improvement] The message sidebar opens next to the toolbar instead of below it, where the toolbar covered the message buttons.
- [Improvement] Inline trace on a page without diagram (e.g. the overview of an API) says where to find it instead of doing nothing. For APIs it works on the Policies tab.
- [Fix] Pretty print of XML no longer inserts Chrome's XSLT deprecation notice into the payload.
- [Fix] CPI Helper starts on the first load after the login redirect, also when the tenant opens on its start page.
- [Fix] The setting to switch off the automatic refresh of the message sidebar works again.
- [Fix] APIs and iFlows on the integration cell show their deploy state again, and the runtime picker marks where they are deployed.
- [Fix] Names and values from traces are escaped before they are shown.
- [Fix] The CPI Helper button in the new shell header opens on the first click and no longer disappears. Thanks to Alexander Aigner.
- [Fix] The CPI Helper popup no longer opens empty the first time. Thanks to Alexander Aigner.
- [Fix] CPI Helper stops cleanly after the extension was reloaded or updated instead of flooding the console. Thanks to Alexander Aigner.
`;
