import { getPage, SHOTS, mask } from "./_lib.mjs";
const { b, page } = await getPage({ create: true });
await page.goto(process.env.CPI_IFLOW_URL);
await page.evaluate(() => (window.name = "paste-probe"));
await page.waitForTimeout(15000);
await page.screenshot({ path: SHOTS + "paste-01-open.png" });
const btns = await page.$$eval("button", (bs) => bs.map((x) => (x.innerText || x.title || x.getAttribute("aria-label") || "").trim()).filter(Boolean));
console.log(btns.join(" | "));
console.log(mask(page.url()));
await b.close();
